language: node_js
node_js:
  - stable

branches:
  only:
    - master

script:
  - npm run coveralls
  - npm run build

deploy:
  provider: npm
  email: pascaldelger@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
